
package quanlidatve;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Loc
 */
public class admin extends javax.swing.JFrame {

     private Connection conn;
    public admin() {
        initComponents();
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt0 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTextFIeid2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        JTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JComboBox1 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông Tin Vé");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MS Vé");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Loại Vé");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Từ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setText("Đến");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("Thời Gian Bay");

        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Tìm Kiếm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Thêm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MS Vé", "Loại Vé", "Từ", "Đến", "Thời Gian Khởi Hành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable2);

        JComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe", "Tàu", "Máy Bay", " " }));
        JComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTextFIeid2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton5)
                                .addGap(26, 26, 26)
                                .addComponent(jButton4)
                                .addGap(25, 25, 25)
                                .addComponent(jButton2)
                                .addGap(27, 27, 27)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(36, 36, 36)
                                .addComponent(JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(155, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(JTextFIeid2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(JTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//thêm
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                                                
    String msVe = txt0.getText();
    String loaiVe = (String) JComboBox1.getSelectedItem();
    String tu = JTextFIeid2.getText();
    String den = JTextField3.getText();
    String thoiGianBay = JTextField.getText();

    // In dữ liệu ra console
    System.out.println("Mã số vé: " + msVe);
    System.out.println("Loại vé: " + loaiVe);
    System.out.println("Từ: " + tu);
    System.out.println("Đến: " + den);
    System.out.println("Thời gian bay: " + thoiGianBay);
    
    // Kiểm tra nếu các trường msVe và tu trống thì không thêm vào bảng
    if (msVe.isEmpty() || tu.isEmpty()) {
        // Thêm thông báo lỗi nếu cần
        JOptionPane.showMessageDialog(null, "Mã số vé và Từ không được để trống.", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } else {
        // Thêm dữ liệu mới vào bảng
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.addRow(new Object[]{msVe, loaiVe, tu, den, thoiGianBay});

        // Xóa nội dung các trường nhập liệu sau khi đã thêm vào bảng
        txt0.setText("");
        JComboBox1.setSelectedIndex(0);
        JTextFIeid2.setText("");
        JTextField3.setText("");
        JTextField.setText("");
    }

                                 
    }//GEN-LAST:event_jButton5ActionPerformed
//Tìm Kiếm
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      // Yêu cầu người dùng nhập từ khóa tìm kiếm
    String searchQuery = JOptionPane.showInputDialog(this, "Enter search query:");

    if (searchQuery != null && !searchQuery.isEmpty()) {
        // Tạo TableRowSorter từ model của jTable2
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        jTable2.setRowSorter(sorter);

        // Áp dụng bộ lọc sử dụng regex, không phân biệt chữ hoa chữ thường
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchQuery));

        // Kiểm tra nếu không có kết quả nào khớp
        if (jTable2.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No matching results found.", "No results", JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        // Hiển thị thông báo nếu người dùng không nhập từ khóa tìm kiếm
        JOptionPane.showMessageDialog(this, "Please enter a search query.", "Empty search query", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jButton4ActionPerformed
//sửa
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    int selectedRowIndex = jTable2.getSelectedRow();

    if (selectedRowIndex != -1) {
        // Lấy dữ liệu từ hàng được chọn
        String msVe = (String) jTable2.getValueAt(selectedRowIndex, 0);
        String loaiVe = (String) jTable2.getValueAt(selectedRowIndex, 1);
        String tu = (String) jTable2.getValueAt(selectedRowIndex, 2);
        String den = (String) jTable2.getValueAt(selectedRowIndex, 3);
        String thoiGianBay = (String) jTable2.getValueAt(selectedRowIndex, 4);

        // Hiển thị cửa sổ hoặc hộp thoại sửa đổi thông tin
        JFrame frame = new JFrame("Sửa thông tin vé");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Tạo các trường nhập liệu để người dùng có thể chỉnh sửa thông tin
        JTextField msVeField = new JTextField(msVe, 20); 
        JComboBox<String> loaiVeComboBox = new JComboBox<>(new String[]{"Phổ Thông", "Đặc Biệt", "VIP"}); 
        loaiVeComboBox.setSelectedItem(loaiVe);
        JTextField tuField = new JTextField(tu, 20);
        JTextField denField = new JTextField(den, 20);
        JTextField thoiGianBayField = new JTextField(thoiGianBay, 20);

        JButton saveButton = new JButton("Lưu");
        saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Lấy thông tin mới từ các trường nhập liệu
                String newMsVe = msVeField.getText();
                String newLoaiVe = loaiVeComboBox.getSelectedItem().toString();
                String newTu = tuField.getText();
                String newDen = denField.getText();
                String newThoiGianBay = thoiGianBayField.getText();

                // Thực hiện việc cập nhật dữ liệu trong bảng
                jTable2.setValueAt(newMsVe, selectedRowIndex, 0);
                jTable2.setValueAt(newLoaiVe, selectedRowIndex, 1);
                jTable2.setValueAt(newTu, selectedRowIndex, 2);
                jTable2.setValueAt(newDen, selectedRowIndex, 3);
                jTable2.setValueAt(newThoiGianBay, selectedRowIndex, 4);

                // Đóng cửa sổ sau khi đã lưu
                frame.dispose();

                // Câu lệnh SQL để cập nhật dữ liệu
                String sql = "UPDATE ten_bang SET msVe = ?, loaiVe = ?, tu = ?, den = ?, thoiGianBay = ? WHERE id = ?";

                try {
                    PreparedStatement statement = conn.prepareStatement(sql);
                    statement.setString(1, newMsVe);
                    statement.setString(2, newLoaiVe);
                    statement.setString(3, newTu);
                    statement.setString(4, newDen);
                    statement.setString(5, newThoiGianBay);
                    String id = null;
                    statement.setString(6, id); // Cần đảm bảo rằng bạn có biến `id` để xác định dòng cần cập nhật
                    int rowsUpdated = statement.executeUpdate();
                    if (rowsUpdated > 0) {
                        System.out.println("Cập nhật thành công");
                    } else {
                        System.out.println("Không có dòng nào được cập nhật");
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        });

        // Tạo panel để chứa các trường nhập liệu và nút lưu
        JPanel panel = new JPanel(new GridLayout(6, 2));
        panel.add(new JLabel("Mã Số Vé:"));
        panel.add(msVeField);
        panel.add(new JLabel("Loại Vé:"));
        panel.add(loaiVeComboBox);
        panel.add(new JLabel("Từ:"));
        panel.add(tuField);
        panel.add(new JLabel("Đến:"));
        panel.add(denField);
        panel.add(new JLabel("Thời Gian Bay:"));
        panel.add(thoiGianBayField);
        panel.add(saveButton);

        // Thêm panel vào frame và hiển thị frame
        frame.getContentPane().add(panel);
        frame.pack();
        frame.setLocationRelativeTo(null); // Hiển thị frame ở giữa màn hình
        frame.setVisible(true);
    } else {
        // Hiển thị thông báo nếu không có hàng nào được chọn
        JOptionPane.showMessageDialog(this, "Please select a row to edit.", "No row selected", JOptionPane.WARNING_MESSAGE);
    }


    }//GEN-LAST:event_jButton2ActionPerformed
//xóa
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int selectedRowIndex = jTable2.getSelectedRow();

    
    if (selectedRowIndex != -1) {
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.removeRow(selectedRowIndex);

       
    } else {
        
        JOptionPane.showMessageDialog(this, "Please select a row to delete.", "No row selected", JOptionPane.WARNING_MESSAGE);
    }

      
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JComboBox1;
    private javax.swing.JTextField JTextFIeid2;
    private javax.swing.JTextField JTextField;
    private javax.swing.JTextField JTextField3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt0;
    // End of variables declaration//GEN-END:variables
}
